logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
spring:
  redis:
    host: 192.168.59.103
    port: 6379
zuul:
  routes:
    ui:
      url: http://localhost:8081
    admin:
      url: http://localhost:8082
    resource:
      url: http://localhost:9000
    uitest:
      url: http://localhost:8085/ui/test