spring:
  security:
    oauth2:
      client:
        registration:
          acme:
            provider: spring
            client-id: acme
            client-secret: acmesecret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/spring"
        provider:
          spring:
            authorization-uri: http://localhost:9999/uaa/oauth2/authorize
            token-uri: http://localhost:9999/uaa/oauth2/token
            user-info-uri: http://localhost:9999/uaa/user
            user-name-attribute: name

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
